// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package models

import (
	"time"
)

type Todo struct {
	ID        int64
	Name      string
	Details   string
	Completed bool
	Created   time.Time
}
