CREATE TABLE todo (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(225) NOT NULL,
  details VARCHAR(16000) NOT NULL DEFAULT '',
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);